Updated index.html with my profiles
anku580/Starter-project-hacktoberfest pull request #4
Opened 2020-10-01 17:00 UTC by BalajiG2000

I have added my github and linkedin profiles in index.html file.

2020-10-01 17:07 UTC, anku580 commented
Hi @BalajiG2000 , there are some conflicts, can you please resolve the conflict?

2020-10-01 17:08 UTC, anku580 requested changes
Please update your PR as per the comments provided. 

Thank you for your valuable contribution.

2020-10-01 17:08 UTC, anku580 commented on index.html
> +      <li><a href="https://github.com/BalajiG2000" target="blank">Balaji</a></li>
Instead of modifying my name, simply add yours in the new `<li> tag.

2020-10-01 17:08 UTC, anku580 commented on index.html
> +      <li><a href="https://www.linkedin.com/in/balaji-g-3bb1a1182/" target="blank">Anku</a></li>
Instead of modifying my name, simply add yours in the new `<li> tag.

2020-10-01 17:15 UTC, BalajiG2000 commented
@anku580  Can you please elaborate? , Should I just add my name and profile , instead of replacing yours?

2020-10-01 17:17 UTC, anku580 commented
@BalajiG2000 yes, insead of removing my name, you can add your name in a new `<li>` tag.

2020-10-01 17:21 UTC, anku580 commented
There are some conflicts with this PR, can you please resolve it and update the PR?

2020-10-01 17:32 UTC, anku580 requested changes
Please don't replace anyone username.

2020-10-01 17:32 UTC, anku580 commented on index.html
> +      <li><a href="https://github.com/BalajiG2000" target="blank">Balaji</a></li>
Please don't replace anyone else username as it would delete it. You can add it one after the other.

2020-10-01 17:32 UTC, anku580 commented on index.html
> +       <li><a href="https://www.linkedin.com/in/balaji-g-3bb1a1182/" target="blank">Anku</a></li>
Please don't replace anyone else username as it would delete it. You can add it one after the other.

2020-10-01 17:43 UTC, anku580 requested changes
Please remove the redundant code.

2020-10-01 17:43 UTC, anku580 commented on index.html
> +<!DOCTYPE html>
Hi buddy, why you have added the duplicated code? You need to remove the duplicate code.

2020-10-02 12:13 UTC, anku580 commented
@BalajiG2000 There are some merge conflicts coming. If you want to learn how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8) created by me.

2020-10-03 07:35 UTC, closed without merging